### ISSUE TITLE
Could you add support for DirectML?

### ISSUE THREAD

**Issue by AshD** [feiyun0112/SemanticKernel.Connectors.OnnxRuntimeGenAI#1]
Thanks for creating this package. 

DirectML support would be very useful for AMD card users. 

Also, Is there a way to fallback from CUDA/DirectML to CPU using Nuget packages. 

Thanks,
Ash

**Comment by feiyun0112** [comment]
have published `feiyun0112.SemanticKernel.Connectors.OnnxRuntimeGenAI.DirectML `

**Comment by AshD** [comment]
Thanks @feiyun0112  
How do I fallback from DirectML to CPU. Is it automatic?
